version: '2'

services:
  redis:
    image: redis

  db:
    image: postgres:9.6
    env_file:
      - env

  app:
    command: daphne -p 8000 -b 0.0.0.0 djangoblog.asgi:channel_layer
    entrypoint: ["./entrypoint.sh"]
    env_file:
      - env
    build:
      context: ./djangoblog
      dockerfile: dockerfile
    depends_on:
      - db
      - redis
      - worker
    links:
      - db
      - redis

  worker:
    command: python manage.py runworker
    env_file:
      - env
    build:
      context: ./djangoblog
      dockerfile: dockerfile
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
