FROM node

ENV SRC /usr/src/ux

RUN mkdir -p ${SRC}
WORKDIR ${SRC}

COPY package.json .
COPY semantic.json .

RUN npm set progress=false
RUN npm install -g -s gulp \
  && npm install -s \
  && npm cache clean
RUN gulp --cwd=semantic-ui build

COPY . ./

VOLUME /usr/src/ux/dist/

CMD npm run build
